name: Test export-solution
on:
  workflow_dispatch:

jobs:
  test-export-solution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: microsoft/powerplatform-actions/export-solution@0.5.0
      with:
        environment-url: ${{ secrets.ENVIRONMENT_URL }}
        solution-name: ${{ secrets.SOLUTION_NAME }}
        app-id: ${{ secrets.APP_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-output-file: out/solution.zip
