name: Test unpack-solution
on:
  workflow_dispatch:

jobs:
  test-unpack-solution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/powerplatform-actions/unpack-solution@0.5.0
      with:
        solution-file: out/solution.zip
        solution-folder: src
